name: Create releases

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Check if version exists
        id: version-check
        run: |
          if npm view ${{ github.event.repository.name }}@${{ steps.package-version.outputs.current-version }} version; then
            echo "Version already exists"
            exit 1
          fi
        continue-on-error: true

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "chore(release): {version}"
          git-user-name: "GitHub Action"
          git-user-email: "action@github.com"
          version-file: "./package.json"
          skip-version-file: true
          skip-git-pull: true
          skip-commit: true

      - name: Build
        run: bun run build

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.current-version }}
          release_name: Release v${{ steps.package-version.outputs.current-version }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false
